[build]
  # No build command needed for functions-only project
  command = "echo 'Functions-only project, no build required'"
  # No publish directory needed
  publish = "."
  # Functions directory (auto-detected but being explicit)
  functions = "netlify/functions"

[functions]
  # Set Node.js version
  node_bundler = "esbuild"

# Optional: Set up redirects if you want to test the form locally
[[redirects]]
  from = "/test"
  to = "/public/squarespace-form.html"
  status = 200